# Generated by Django 4.0.5 on 2022-07-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='no_of_persons',
            field=models.IntegerField(default=1),
        ),
    ]
