# Generated by Django 4.0.5 on 2022-07-08 13:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_persons_number_remove_booking_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='featured_image',
            new_name='table_free_img',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.AddField(
            model_name='table',
            name='table_occupied_img',
            field=cloudinary.models.CloudinaryField(default='table_image', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
