# Generated by Django 4.0.5 on 2022-07-08 14:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_table_free_img_table_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='table',
            name='table_free_img',
            field=cloudinary.models.CloudinaryField(default='free_image', max_length=255, verbose_name='free_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='table_occupied_img',
            field=cloudinary.models.CloudinaryField(default='occupied_image', max_length=255, verbose_name='occupied_image'),
            preserve_default=False,
        ),
    ]
