# Generated by Django 4.0.6 on 2022-07-15 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='booking.table', to_field='code'),
        ),
    ]
