# Generated by Django 4.1 on 2022-08-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_bookingquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(default='2022-08-18 13:18:22'),
        ),
    ]
