# Generated by Django 4.1 on 2022-08-25 13:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_booking_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_free_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_occupied_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
