# Generated by Django 4.1 on 2022-08-25 13:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_table_table_free_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_free_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='free_image'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_occupied_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='occupied_image'),
        ),
    ]
