# Generated by Django 4.0.6 on 2022-07-22 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('date_created_on', models.DateField(auto_now=True)),
                ('time_created_on', models.TimeField()),
                ('date_updated_on', models.DateField(auto_now_add=True)),
                ('time_updated_on', models.TimeField()),
                ('rate', models.PositiveSmallIntegerField()),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
            options={
                'ordering': ['date_updated_on', 'time_updated_on'],
            },
        ),
    ]
