# Generated by Django 4.0.6 on 2022-07-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['date_updated_on']},
        ),
    ]
